### ISSUE TITLE
API needs https

### ISSUE THREAD

**Issue by jondkinney** [michaelparenteau/gemv.alfredworkflow#1]
Hi there, I had to update the API url to be `https://` for it to work for me locally.

Didn't see how to add a PR for the shell script since it looks compiled here in the repo.

**Comment by michaelparenteau** [comment]
@jondkinney Thanks for the heads up.. just pushed up the new version. I just recloned the repo (I have a new machine) and exported the changed workflow into the repo, git picked up the change and let me push... did you try exporting the compiled workflow into the repo? Either way, I made the change to https and it is now current. Thanks again!

**Comment by jondkinney** [comment]
Thank you for a useful workflow! :+1:
